<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1FLO5NT" failures="1" tests="3" name="Default test" time="20.229" errors="0" timestamp="2025-01-20T18:50:07 IST">
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.995"/>
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.733">
    <failure type="java.lang.AssertionError" message="
Expecting actual:
  &amp;quot;https://www.saucedemo.com/&amp;quot;
to contain:
  &amp;quot;inventory&amp;quot; ">
      <![CDATA[java.lang.AssertionError: 
Expecting actual:
  "https://www.saucedemo.com/"
to contain:
  "inventory" 
at com.mk.tests.LoginTest.loginTest(LoginTest.java:21)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.993"/>
</testsuite> <!-- Default test -->
