<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1FLO5NT" failures="6" tests="6" name="Test1" time="53.127" errors="0" timestamp="2025-01-12T12:29:25 IST">
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.543">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.975">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.453">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.492">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="0.478">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mk.tests.LoginTest" name="loginTest" time="5.493">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.mk.tests.LoginTest.loginTest(LoginTest.java:24)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test1 -->
